// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD5-iLC2U3vEQr4hc14Mrnad2m6kdIrebE',
    appId: '1:987419862779:web:d158aca3135a2b9d64f25e',
    messagingSenderId: '987419862779',
    projectId: 'spotify-20254411',
    authDomain: 'spotify-20254411.firebaseapp.com',
    storageBucket: 'spotify-20254411.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBD_4LcS4QScIkxaKFQV8h-2eHdN9kDuQ4',
    appId: '1:987419862779:android:de2c1419b8ff9ea364f25e',
    messagingSenderId: '987419862779',
    projectId: 'spotify-20254411',
    storageBucket: 'spotify-20254411.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC9eS0ned9VB2WsRJGTpVat-II3gkgT2yk',
    appId: '1:987419862779:ios:3dcf70e43ca6432264f25e',
    messagingSenderId: '987419862779',
    projectId: 'spotify-20254411',
    storageBucket: 'spotify-20254411.appspot.com',
    iosBundleId: 'com.example.spotifyClone',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC9eS0ned9VB2WsRJGTpVat-II3gkgT2yk',
    appId: '1:987419862779:ios:3dcf70e43ca6432264f25e',
    messagingSenderId: '987419862779',
    projectId: 'spotify-20254411',
    storageBucket: 'spotify-20254411.appspot.com',
    iosBundleId: 'com.example.spotifyClone',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD5-iLC2U3vEQr4hc14Mrnad2m6kdIrebE',
    appId: '1:987419862779:web:60bcecb01432071764f25e',
    messagingSenderId: '987419862779',
    projectId: 'spotify-20254411',
    authDomain: 'spotify-20254411.firebaseapp.com',
    storageBucket: 'spotify-20254411.appspot.com',
  );

}